# Generated by Django 5.2.7 on 2025-11-18 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, verbose_name='nome')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('pontos', models.PositiveIntegerField(default=0, verbose_name='Ponto')),
                ('avatar', models.URLField(blank=True, null=True, verbose_name='Avatar(URL)')),
            ],
        ),
    ]
